config/routes.rb
Rails.application.routes.draw do

  devise_for :users  

  resources :messages, :only => [:index, :new, :create, :show]
  
  resources :members do
  	post 'add_group'
  	delete 'remove_group/:group_id' => 'members#remove_group', :as => 'remove_from_group'
  end

  resources :groups do 
  	delete 'remove_member/:member_id' => 'groups#remove_member', :as => 'remove_member'
  end

  root 'members#index'

end

app/models/message.rb
class Message
  
  include Mongoid::Document
  field :title, type: String
  field :description, type: String

  has_many :groups

  accepts_nested_attributes_for :groups

  after_create :prepare_emails

  def prepare_emails
  	members = []
  	self.groups.each do |group|
  		members += group.members
  	end

  	members = members.uniq

  	if members.count <= 50
  		self.send_email(members)
  	else
  		chunks = members.each_slice(50).to_a
  		chunks.each do |chunk|
  			self.send_email(chunk)
  		end
  	end
  end

  def send_email(members)
  	emails = members.collect{ |m| m.workemailaddress }
  	MembersMailer.new_message(emails, self.title, self.description).deliver
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all.paginate(:page => params[:page], :per_page => 25)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
    @groups = Group.order("name ASC")
  end

  # POST /messages
  # POST /messages.json
  def create
    groups_list = params[:message][:groups].split(',')
    @message = Message.new(message_params)

    groups_list.each do |g|
      @message.groups << Group.find(g)
    end

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :description)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, "Titulo" %><br>
    <%= f.text_field :title, :class => 'form-control', :required => true %>
  </div>
  <div class="field form-group">
    <%= f.label :description, "Mensaje" %><br>
    <%= f.text_area :description, :class => 'form-control', :required => true %>
  </div>

  <div>
    <strong>Grupos</strong>

    <%= select_tag :groups_items, options_from_collection_for_select(@groups, "id", "name"), {:class => 'form-control'} %>
    <br />
    <%= link_to "Agregar", 'javascript:void(0)', :class => "btn btn-default", :id => 'add_group' %>
    <br /><br />

    <div id="groups_data">
    </div>
  </div>

  <br />

  <hr />

  <div class="actions">
    <%= f.hidden_field :groups %>
    <%= link_to 'Regresar', messages_path, :class => "btn btn-default" %>
    <%= f.submit "Enviar", :class => "btn btn-default" %>
  </div>
<% end %>

<script type="text/javascript">
var groups = [];

$(document).ready(function(){
  $('#add_group').click(function(){
      var value = $("#groups_items").val();
        
      var found = false;
      for(i=0; i<groups.length; i++){
        if(groups[i] == value){
          found = true;
          break;
        }
      }

      if(!found){
        groups.push(value);
        $('#groups_data').append('<div id="group_' + value + '">' + $('#groups_items option:selected').text() + ' <a href="javascript:removeGroup(\'' + value + '\')">Eliminar</a></div>');
      }

      $('#message_groups').val(groups);
  });  
});

function removeGroup(value){
  $('#group_' + value).remove();

  var new_groups = [];
  for(i=0; i<groups.length; i++){
    if(groups[i] != value){
      new_groups.push(groups[i]);
    }
  }

  groups = new_groups;
  $('#message_groups').val(groups);
}
</script>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mensajes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Mensaje</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title %></td>
        <td><%= message.description %></td>
        <td><%= link_to 'Mostrar', message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @messages %>

<br>

<%= link_to 'Nuevo  mensaje', new_message_path, :class => "btn btn-default" %>

app/views/messages/new.html.erb
<h1>Nuevo Mensaje</h1>

<%= render 'form' %>

app/views/messages/show.html.erb
<h1>Mensaje</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= @message.title %></strong>
</p>

<p>
  <%= @message.description %>
</p>

<div>
	<strong>Grupos</strong>

	<table>
		<% @message.groups.each do |group| %>
			<tr>
				<td>
					<%= link_to group.name, group %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

<hr />

<%= link_to 'Regresar', messages_path, :class => "btn btn-default" %>