config/routes.rb
Rails.application.routes.draw do

  devise_for :users  

  resources :messages, :only => [:index, :new, :create, :show]
  
  resources :members do
  	post 'add_group'
  	delete 'remove_group/:group_id' => 'members#remove_group', :as => 'remove_from_group'
  end

  resources :groups do 
  	delete 'remove_member/:member_id' => 'groups#remove_member', :as => 'remove_member'
  end

  root 'members#index'

end

app/models/group.rb
class Group
  include Mongoid::Document
  
  field :name, type: String
  field :description, type: String

  has_many :group_members
  belongs_to :message

  def members
  	group_members.collect{ |gm| gm.member }
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group_members = @group.group_members
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'El grupo ha sido creado' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'El grupo ha sido actualizado' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'El grupo ha sido eliminado' }
      format.json { head :no_content }
    end
  end

  def remove_member
    @member = Member.find(params[:member_id])
    @group_member_id = @member.remove_group(params[:group_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :description, "Descripción" %><br>
    <%= f.text_field :description, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= link_to 'Regresar', groups_path, :class => "btn btn-default" %>
    <%= f.submit "Guardar", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/groups/_group_member.html.erb
<tr id="group_member_<%= group_member.id %>">
	<td><%= group_member.member.fullname %></td>
	<td><%= link_to 'Eliminar', group_remove_member_path(group_member.group, group_member.member), method: :delete, remote: true, data: { confirm: '¿Esta seguro de querer eliminar este miembro?' } %></td>
</tr>

app/views/groups/edit.html.erb
<h1>Edición de Grupo</h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<h1>Grupos</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group %></td>
        <td><%= group.description %></td>
        <td><%= link_to 'Editar', edit_group_path(group) %></td>
        <td><%= link_to 'Eliminar', group, method: :delete, data: { confirm: '¿Esta seguro de querer eliminar este grupo?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo grupo', new_group_path, :class => "btn btn-default" %>

app/views/groups/new.html.erb
<h1>Nuevo Grupo</h1>

<%= render 'form' %>

app/views/groups/remove_member.js.erb
<% if @group_member_id > 0 %>
	$('#group_member_<%= @group_member_id %>').remove();
<% end %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>

<p>
  <%= @group.description %>
</p>

<hr />

<h3>Miembros</h3>

<div>
	<table class="table table-bordered">
	  <thead>
	    <tr>
	      <th>Miembro</th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody id="group_members">
	    <%= render :partial => 'group_member', :collection => @group_members %>
	  </tbody>
	</table>
</div>

<%= link_to 'Editar', edit_group_path(@group), :class => "btn btn-default" %>
<%= link_to 'Volver', groups_path, :class => "btn btn-default" %>