config/routes.rb
Rails.application.routes.draw do

  devise_for :users  

  resources :messages, :only => [:index, :new, :create, :show]
  
  resources :members do
  	post 'add_group'
  	delete 'remove_group/:group_id' => 'members#remove_group', :as => 'remove_from_group'
  end

  resources :groups do 
  	delete 'remove_member/:member_id' => 'groups#remove_member', :as => 'remove_member'
  end

  root 'members#index'

end

app/models/member.rb
class Member
  include Mongoid::Document
  field :salutation, type: String
  field :firstname, type: String
  field :lastname, type: String
  field :organisation, type: String
  field :role, type: String
  field :background, type: String
  field :businessstreet, type: String #check
  field :businesscity, type: String
  field :businessstate, type: String
  field :businesspostalcode, type: String
  field :businesscountry, type: String
  field :homestreet, type: String
  field :homecity, type: String
  field :homestate, type: String
  field :homepostalcode, type: String
  field :homecountry, type: String
  field :otherstreet, type: String
  field :othercity, type: String
  field :otherstate, type: String
  field :otherpostalcode, type: String
  field :othercountry, type: String
  field :postalstreet, type: String
  field :postalcity, type: String
  field :postalstate, type: String
  field :postalpostalcode, type: String
  field :postalcountry, type: String
  field :businessphone, type: String
  field :businessphone2, type: String
  field :businessfax, type: String
  field :homephone, type: String
  field :homephone2, type: String
  field :mobilephone, type: String
  field :otherphone, type: String
  field :pagerphone, type: String
  field :skypephone, type: String
  field :sipphone, type: String
  field :workemailaddress, type: String
  field :personalemailaddress, type: String
  field :otheremailaddress, type: String
  field :workwebsite, type: String
  field :personalwebsite, type: String
  field :blogwebsite, type: String
  field :otherwebsite, type: String
  field :importantdate1name, type: String
  field :importantdate1, type: String
  field :importantdate2name, type: String
  field :importantdate2, type: String
  field :importantdate3name, type: String
  field :importantdate3, type: String
  field :contacttag1, type: String
  field :contacttag2, type: String
  field :contacttag3, type: String
  field :contacttag4, type: String
  field :contacttag5, type: String
  field :contacttag6, type: String
  field :contacttag7, type: String
  field :contacttag8, type: String
  field :contacttag9, type: String
  field :datecreated, type: String
  field :dateupdated, type: String
  field :linkedorganizationpostalstreet, type: String
  field :linkedorganizationpostalcity, type: String
  field :linkedorganizationpostalstate, type: String
  field :linkedorganizationpostalcode, type: String
  field :linkedorganizationpostalcountry, type: String
  field :linkedorganizationbusinessstreet, type: String
  field :linkedorganizationbusinesscity, type: String
  field :linkedorganizationbusinessstate, type: String
  field :linkedorganizationbusinesspostalcode, type: String
  field :linkedorganizationbusinesscountry, type: String
  field :fecha_de_nacimiento, type: String
  field :estado_civil, type: String
  field :campus_al_que_asiste, type: String
  field :es, type: String
  field :nivel_de_discipulado, type: String
  field :nombre_de_discipulador, type: String
  field :grupo_pequeo_al_que_asiste, type: String
  field :ler_de_grupo_pequeo, type: String
  field :ministerios_en_los_que_sirve, type: String
  field :talentos, type: String

  has_many :group_members

  def fullname
    self.firstname + " " + self.lastname
  end

  def add_group(group_id)
    gm = self.group_members.where(group_id: group_id)

    if gm.empty?
      gm = GroupMember.create(group_id: group_id, member_id: self.id)
      gm.save

      return gm
    else
      return nil
    end
  end

  def remove_group(group_id)
    gm = self.group_members.where(group_id: group_id)
    gm_id = gm.first.id
    gm.destroy_all

    return gm_id
  end

  def self.get_members(kind, search)
    search_items = search.split.collect{ |i| Regexp.new (".*" + i + ".*") }

    case kind 
      when 1
        results = Member.or(:firstname.in => search_items).or(:lastname.in => search_items)
      when 2
        results = Member.where(workemailaddress: search)
      when 3
        results = Member.or(:campus_al_que_asiste.in => search_items)
      when 4
        results = Member.or(:nombre_de_discipulador.in => search_items)
      when 5
        results = Member.or(:grupo_pequeo_al_que_asiste.in => search_items)
      when 6
        results = Member.or(:ministerios_en_los_que_sirve.in => search_items)
      when 0
        results = Member.or(:firstname.in => search_items).or(:lastname.in => search_items).or(:workemailaddress.in => search_items).or(:campus_al_que_asiste.in => search_items).or(:nombre_de_discipulador.in => search_items).or(:grupo_pequeo_al_que_asiste.in => search_items).or(:ministerios_en_los_que_sirve.in => search_items)
      else
    end

    return results
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    if params[:data]
      @members = Member.get_members(params[:data][:kind].to_i, params[:data][:search])
    else
      @members = Member.all
    end

    @members = @members.paginate(:page => params[:page], :per_page => 25)
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
    @creating_member = true
  end

  # GET /members/1/edit
  def edit
    @groups = Group.all.order('name ASC')
    @group_members = @member.group_members
    @creating_member = false
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @creating_member = true

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'El miembro ha sido creado' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    @creating_member = false

    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'El miembro ha sido actualizado' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'El miembro ha sido eliminado' }
      format.json { head :no_content }
    end
  end

  def add_group
    @member = Member.find(params[:member_id])
    @group_member = @member.add_group(params[:data][:group_id])
  end

  def remove_group
    @member = Member.find(params[:member_id])
    @group_member_id = @member.remove_group(params[:group_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:salutation, :firstname, :lastname, :organisation, :role, :background, :businessstreet, :businesscity, :businessstate, :businesspostalcode, :businesscountry, :homestreet, :homecity, :homestate, :homepostalcode, :homecountry, :otherstreet, :othercity, :otherstate, :otherpostalcode, :othercountry, :postalstreet, :postalcity, :postalstate, :postalpostalcode, :postalcountry, :businessphone, :businessphone2, :businessfax, :homephone, :homephone2, :mobilephone, :otherphone, :pagerphone, :skypephone, :sipphone, :workemailaddress, :personalemailaddress, :otheremailaddress, :workwebsite, :personalwebsite, :blogwebsite, :otherwebsite, :importantdate1name, :importantdate1, :importantdate2name, :importantdate2, :importantdate3name, :importantdate3, :contacttag1, :contacttag2, :contacttag3, :contacttag4, :contacttag5, :contacttag6, :contacttag7, :contacttag8, :contacttag9, :datecreated, :dateupdated, :linkedorganizationpostalstreet, :linkedorganizationpostalcity, :linkedorganizationpostalstate, :linkedorganizationpostalcode, :linkedorganizationpostalcountry, :linkedorganizationbusinessstreet, :linkedorganizationbusinesscity, :linkedorganizationbusinessstate, :linkedorganizationbusinesspostalcode, :linkedorganizationbusinesscountry, :fecha_de_nacimiento, :estado_civil, :campus_al_que_asiste, :es, :nivel_de_discipulado, :nombre_de_discipulador, :grupo_pequeo_al_que_asiste, :ler_de_grupo_pequeo, :ministerios_en_los_que_sirve, :talentos)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :firstname, "Nombre" %><br>
    <%= f.text_field :firstname, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :lastname, "Apellido" %><br>
    <%= f.text_field :lastname, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :homestreet, "Direccion" %><br>
    <%= f.text_field :homestreet, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :homecity, "Colonia" %><br>
    <%= f.text_field :homecity, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :businessphone, "Telefono" %><br>
    <%= f.text_field :businessphone, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :workemailaddress, "Email" %><br>
    <%= f.text_field :workemailaddress, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :fecha_de_nacimiento %><br>
    <%= f.text_field :fecha_de_nacimiento, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :estado_civil %><br>
    <%= f.text_field :estado_civil, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :campus_al_que_asiste, "Campus" %><br>
    <%= f.text_field :campus_al_que_asiste, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :es, "Estado" %><br>
    <%= f.text_field :es, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :nivel_de_discipulado %><br>
    <%= f.text_field :nivel_de_discipulado, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :nombre_de_discipulador %><br>
    <%= f.text_field :nombre_de_discipulador, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :grupo_pequeo_al_que_asiste, "Grupo pequeño al que asiste" %><br>
    <%= f.text_field :grupo_pequeo_al_que_asiste, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :ler_de_grupo_pequeo, "Lider de grupo pequeño" %><br>
    <%= f.text_field :ler_de_grupo_pequeo, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :ministerios_en_los_que_sirve %><br>
    <%= f.text_field :ministerios_en_los_que_sirve, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :talentos %><br>
    <%= f.text_area :talentos, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= link_to 'Regresar', members_path, :class => "btn btn-default" %>
    <%= f.submit "Guardar", :class => "btn btn-default" %>
  </div>
<% end %>

<% if !@creating_member %>
  <hr />

  <div>
    <h3>Grupos</h3>

    <%= form_for :data, :url => member_add_group_path(@member), :remote => true do |f| %>
      <div class="field form-group">
        <%= f.select :group_id, @groups.collect{ |c| [c.name, c.id] }, {}, :class => 'form-control' %>
      </div>

      <div class="actions right">
        <%= f.submit 'Agregar', :class => "btn btn-default" %>
      </div>
    <% end %>
  </div>

  <hr />

  <div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Grupo</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="group_members">
        <%= render :partial => 'group_member', :collection => @group_members %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/members/_group_member.html.erb
<tr id="group_member_<%= group_member.id %>">
	<td><%= group_member.group.name %></td>
	<td><%= link_to 'Eliminar', member_remove_from_group_path(group_member.member, group_member.group), method: :delete, remote: true, data: { confirm: '¿Esta seguro de querer eliminar este grupo?' } %></td>
</tr>

app/views/members/add_group.js.erb
<% if !@group_member.nil? %>
	$('#group_members').append("<%=j render :partial => 'group_member', :object => @group_member %>");
<% else %>
	alert('El miembro ya se encuentra en el grupo');
<% end %>

app/views/members/edit.html.erb
<h1>Edición de Miembro</h1>

<%= render 'form' %>

app/views/members/index.html.erb
<h1>Miembros</h1>

<hr />

<div>
  <%= form_for :data, :class => "form-inline", :method => "GET" do |f| %>
    <div class="field form-group">
      <% search_value = params[:data][:search] rescue "" %>
      <%= f.text_field :search, :value => search_value, :class => 'form-control', :placeholder => 'Buscar' %>
      <% selected_option = params[:data][:kind].to_i rescue 0 %>
      <%= f.select :kind,  [["Todo", 0], ["Nombre", 1], ["Email", 2], ["Campus", 3], ["Discipulador", 4], ["Grupo pequeño", 5], ["Ministerios", 6]], {:selected => selected_option}, :class => 'form-control'  %>
    </div>
    
    <div class="actions right">
      <%= f.submit "Buscar", :class => "btn btn-default" %>
    </div>
  <% end %>
</div>

<hr />

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Email</th>
      <th>Fecha de nacimiento</th>
      <th>Estado civil</th>
      <th>Campus</th>
      <th>Nivel de discipulado</th>
      <th>Nombre de discipulador</th>
      <th>Grupo pequeño</th>
      <th>Lider de grupo pequeño</th>
      <th>Ministerios</th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.fullname, edit_member_path(member) %></td>
        <td><%= member.businessphone %></td>
        <td><%= member.workemailaddress %></td>
        <td><%= member.fecha_de_nacimiento %></td>
        <td><%= member.estado_civil %></td>
        <td><%= member.campus_al_que_asiste %></td>
        <td><%= member.nivel_de_discipulado %></td>
        <td><%= member.nombre_de_discipulador %></td>
        <td><%= member.grupo_pequeo_al_que_asiste %></td>
        <td><%= member.ler_de_grupo_pequeo %></td>
        <td><%= member.ministerios_en_los_que_sirve %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @members %>

<br>

<%= link_to 'Nuevo miembro', new_member_path, :class => "btn btn-default" %>

app/views/members/new.html.erb
<h1>Nuevo Miembro</h1>

<%= render 'form' %>

app/views/members/remove_group.js.erb
<% if @group_member_id > 0 %>
	$('#group_member_<%= @group_member_id %>').remove();
<% end %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Salutation:</strong>
  <%= @member.salutation %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @member.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @member.lastname %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @member.organisation %>
</p>

<p>
  <strong>Role:</strong>
  <%= @member.role %>
</p>

<p>
  <strong>Background:</strong>
  <%= @member.background %>
</p>

<p>
  <strong>Businessstreet:</strong>
  <%= @member.businessstreet %>
</p>

<p>
  <strong>Businesscity:</strong>
  <%= @member.businesscity %>
</p>

<p>
  <strong>Businessstate:</strong>
  <%= @member.businessstate %>
</p>

<p>
  <strong>Businesspostalcode:</strong>
  <%= @member.businesspostalcode %>
</p>

<p>
  <strong>Businesscountry:</strong>
  <%= @member.businesscountry %>
</p>

<p>
  <strong>Homestreet:</strong>
  <%= @member.homestreet %>
</p>

<p>
  <strong>Homecity:</strong>
  <%= @member.homecity %>
</p>

<p>
  <strong>Homestate:</strong>
  <%= @member.homestate %>
</p>

<p>
  <strong>Homepostalcode:</strong>
  <%= @member.homepostalcode %>
</p>

<p>
  <strong>Homecountry:</strong>
  <%= @member.homecountry %>
</p>

<p>
  <strong>Otherstreet:</strong>
  <%= @member.otherstreet %>
</p>

<p>
  <strong>Othercity:</strong>
  <%= @member.othercity %>
</p>

<p>
  <strong>Otherstate:</strong>
  <%= @member.otherstate %>
</p>

<p>
  <strong>Otherpostalcode:</strong>
  <%= @member.otherpostalcode %>
</p>

<p>
  <strong>Othercountry:</strong>
  <%= @member.othercountry %>
</p>

<p>
  <strong>Postalstreet:</strong>
  <%= @member.postalstreet %>
</p>

<p>
  <strong>Postalcity:</strong>
  <%= @member.postalcity %>
</p>

<p>
  <strong>Postalstate:</strong>
  <%= @member.postalstate %>
</p>

<p>
  <strong>Postalpostalcode:</strong>
  <%= @member.postalpostalcode %>
</p>

<p>
  <strong>Postalcountry:</strong>
  <%= @member.postalcountry %>
</p>

<p>
  <strong>Businessphone:</strong>
  <%= @member.businessphone %>
</p>

<p>
  <strong>Businessphone2:</strong>
  <%= @member.businessphone2 %>
</p>

<p>
  <strong>Businessfax:</strong>
  <%= @member.businessfax %>
</p>

<p>
  <strong>Homephone:</strong>
  <%= @member.homephone %>
</p>

<p>
  <strong>Homephone2:</strong>
  <%= @member.homephone2 %>
</p>

<p>
  <strong>Mobilephone:</strong>
  <%= @member.mobilephone %>
</p>

<p>
  <strong>Otherphone:</strong>
  <%= @member.otherphone %>
</p>

<p>
  <strong>Pagerphone:</strong>
  <%= @member.pagerphone %>
</p>

<p>
  <strong>Skypephone:</strong>
  <%= @member.skypephone %>
</p>

<p>
  <strong>Sipphone:</strong>
  <%= @member.sipphone %>
</p>

<p>
  <strong>Workemailaddress:</strong>
  <%= @member.workemailaddress %>
</p>

<p>
  <strong>Personalemailaddress:</strong>
  <%= @member.personalemailaddress %>
</p>

<p>
  <strong>Otheremailaddress:</strong>
  <%= @member.otheremailaddress %>
</p>

<p>
  <strong>Workwebsite:</strong>
  <%= @member.workwebsite %>
</p>

<p>
  <strong>Personalwebsite:</strong>
  <%= @member.personalwebsite %>
</p>

<p>
  <strong>Blogwebsite:</strong>
  <%= @member.blogwebsite %>
</p>

<p>
  <strong>Otherwebsite:</strong>
  <%= @member.otherwebsite %>
</p>

<p>
  <strong>Importantdate1name:</strong>
  <%= @member.importantdate1name %>
</p>

<p>
  <strong>Importantdate1:</strong>
  <%= @member.importantdate1 %>
</p>

<p>
  <strong>Importantdate2name:</strong>
  <%= @member.importantdate2name %>
</p>

<p>
  <strong>Importantdate2:</strong>
  <%= @member.importantdate2 %>
</p>

<p>
  <strong>Importantdate3name:</strong>
  <%= @member.importantdate3name %>
</p>

<p>
  <strong>Importantdate3:</strong>
  <%= @member.importantdate3 %>
</p>

<p>
  <strong>Contacttag1:</strong>
  <%= @member.contacttag1 %>
</p>

<p>
  <strong>Contacttag2:</strong>
  <%= @member.contacttag2 %>
</p>

<p>
  <strong>Contacttag3:</strong>
  <%= @member.contacttag3 %>
</p>

<p>
  <strong>Contacttag4:</strong>
  <%= @member.contacttag4 %>
</p>

<p>
  <strong>Contacttag5:</strong>
  <%= @member.contacttag5 %>
</p>

<p>
  <strong>Contacttag6:</strong>
  <%= @member.contacttag6 %>
</p>

<p>
  <strong>Contacttag7:</strong>
  <%= @member.contacttag7 %>
</p>

<p>
  <strong>Contacttag8:</strong>
  <%= @member.contacttag8 %>
</p>

<p>
  <strong>Contacttag9:</strong>
  <%= @member.contacttag9 %>
</p>

<p>
  <strong>Datecreated:</strong>
  <%= @member.datecreated %>
</p>

<p>
  <strong>Dateupdated:</strong>
  <%= @member.dateupdated %>
</p>

<p>
  <strong>Linkedorganizationpostalstreet:</strong>
  <%= @member.linkedorganizationpostalstreet %>
</p>

<p>
  <strong>Linkedorganizationpostalcity:</strong>
  <%= @member.linkedorganizationpostalcity %>
</p>

<p>
  <strong>Linkedorganizationpostalstate:</strong>
  <%= @member.linkedorganizationpostalstate %>
</p>

<p>
  <strong>Linkedorganizationpostalcode:</strong>
  <%= @member.linkedorganizationpostalcode %>
</p>

<p>
  <strong>Linkedorganizationpostalcountry:</strong>
  <%= @member.linkedorganizationpostalcountry %>
</p>

<p>
  <strong>Linkedorganizationbusinessstreet:</strong>
  <%= @member.linkedorganizationbusinessstreet %>
</p>

<p>
  <strong>Linkedorganizationbusinesscity:</strong>
  <%= @member.linkedorganizationbusinesscity %>
</p>

<p>
  <strong>Linkedorganizationbusinessstate:</strong>
  <%= @member.linkedorganizationbusinessstate %>
</p>

<p>
  <strong>Linkedorganizationbusinesspostalcode:</strong>
  <%= @member.linkedorganizationbusinesspostalcode %>
</p>

<p>
  <strong>Linkedorganizationbusinesscountry:</strong>
  <%= @member.linkedorganizationbusinesscountry %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @member.fecha_de_nacimiento %>
</p>

<p>
  <strong>Estado civil:</strong>
  <%= @member.estado_civil %>
</p>

<p>
  <strong>Campus al que asiste:</strong>
  <%= @member.campus_al_que_asiste %>
</p>

<p>
  <strong>Es:</strong>
  <%= @member.es %>
</p>

<p>
  <strong>Nivel de discipulado:</strong>
  <%= @member.nivel_de_discipulado %>
</p>

<p>
  <strong>Nombre de discipulador:</strong>
  <%= @member.nombre_de_discipulador %>
</p>

<p>
  <strong>Grupo pequeo al que asiste:</strong>
  <%= @member.grupo_pequeo_al_que_asiste %>
</p>

<p>
  <strong>Ler de grupo pequeo:</strong>
  <%= @member.ler_de_grupo_pequeo %>
</p>

<p>
  <strong>Ministerios en los que sirve:</strong>
  <%= @member.ministerios_en_los_que_sirve %>
</p>

<p>
  <strong>Talentos:</strong>
  <%= @member.talentos %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>